//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobTalentAssociations = new HashSet<JobTalentAssociation>();
            this.JobTalentCategories = new HashSet<JobTalentCategory>();
            this.JobTalentLanguages = new HashSet<JobTalentLanguage>();
            this.JobTalentSkills = new HashSet<JobTalentSkill>();
            this.Media = new HashSet<Medium>();
        }
    
        public long JobId { get; set; }
        public string JobName { get; set; }
        public long ProductionCompanyId { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<long> RegionId { get; set; }
        public string JobDescription { get; set; }
        public string Gender { get; set; }
        public long MinAge { get; set; }
        public long MaxAge { get; set; }
        public string EyeColor { get; set; }
        public Nullable<long> Height { get; set; }
        public Nullable<long> Waist { get; set; }
        public string HairColor { get; set; }
        public Nullable<long> ChestSize { get; set; }
        public Nullable<long> HipSize { get; set; }
        public string Ethicity { get; set; }
        public string Pay { get; set; }
        public Nullable<long> NumberOfDays { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
    
        public virtual ProductionCompany ProductionCompany { get; set; }
        public virtual Region Region { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<JobTalentAssociation> JobTalentAssociations { get; set; }
        public virtual ICollection<JobTalentCategory> JobTalentCategories { get; set; }
        public virtual ICollection<JobTalentLanguage> JobTalentLanguages { get; set; }
        public virtual ICollection<JobTalentSkill> JobTalentSkills { get; set; }
        public virtual ICollection<Medium> Media { get; set; }
    }
}
