//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTalentAssociation
    {
        public long JobTalentAssociationId { get; set; }
        public long JobId { get; set; }
        public long TalentId { get; set; }
        public long Status { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Role { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Talent Talent { get; set; }
    }
}
