//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public SubCategory()
        {
            this.ContactUs = new HashSet<ContactU>();
            this.Jobs = new HashSet<Job>();
            this.JobTalentAssociations = new HashSet<JobTalentAssociation>();
            this.JobTalentCategories = new HashSet<JobTalentCategory>();
            this.JobTalentLanguages = new HashSet<JobTalentLanguage>();
            this.JobTalentSkills = new HashSet<JobTalentSkill>();
            this.Talents = new HashSet<Talent>();
            this.Talents1 = new HashSet<Talent>();
        }
    
        public long SubCategoryId { get; set; }
        public long CategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public string SubCategoryValue { get; set; }
        public string SubCategoryDescription { get; set; }
        public Nullable<long> ParentId { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ContactU> ContactUs { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<JobTalentAssociation> JobTalentAssociations { get; set; }
        public virtual ICollection<JobTalentCategory> JobTalentCategories { get; set; }
        public virtual ICollection<JobTalentLanguage> JobTalentLanguages { get; set; }
        public virtual ICollection<JobTalentSkill> JobTalentSkills { get; set; }
        public virtual ICollection<Talent> Talents { get; set; }
        public virtual ICollection<Talent> Talents1 { get; set; }
    }
}
